// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRTO8WPzzZeQco3Nx87Muq-zW76O80hOU',
    appId: '1:411928064781:web:bd4001ee476c903f29f644',
    messagingSenderId: '411928064781',
    projectId: 'auth-84f49',
    authDomain: 'auth-84f49.firebaseapp.com',
    storageBucket: 'auth-84f49.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaRFH75vOUeQkeHpwtugQYSArTeIajjeo',
    appId: '1:411928064781:android:34f6d958737dec1b29f644',
    messagingSenderId: '411928064781',
    projectId: 'auth-84f49',
    storageBucket: 'auth-84f49.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoG9GoVHmvQUI6ABe2AZUthjgnWBivo9w',
    appId: '1:411928064781:ios:cb0fc7fecb09053029f644',
    messagingSenderId: '411928064781',
    projectId: 'auth-84f49',
    storageBucket: 'auth-84f49.appspot.com',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoG9GoVHmvQUI6ABe2AZUthjgnWBivo9w',
    appId: '1:411928064781:ios:cb0fc7fecb09053029f644',
    messagingSenderId: '411928064781',
    projectId: 'auth-84f49',
    storageBucket: 'auth-84f49.appspot.com',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRTO8WPzzZeQco3Nx87Muq-zW76O80hOU',
    appId: '1:411928064781:web:0319f76beaf9056429f644',
    messagingSenderId: '411928064781',
    projectId: 'auth-84f49',
    authDomain: 'auth-84f49.firebaseapp.com',
    storageBucket: 'auth-84f49.appspot.com',
  );
}
